/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      backgroundColor: {
        'primary-light': '#B9B8B8',
        'primary-dark': '#606060',
        'brand-primary': 'var(--color-primary)',
        'brand-primary-hover': 'var(--color-primary-hover)',
        'brand-secondary': 'var(--color-secondary)',
        'brand-secondary-hover': 'var(--color-secondary-hover)',
        'brand-accent': 'var(--color-accent)',
        'brand-bg': 'var(--color-bg)',
        'brand-bg-secondary': 'var(--color-bg-secondary)',
        'brand-success': 'var(--color-success)',
        'brand-error': 'var(--color-error)',
        'brand-warning': 'var(--color-warning)',
      },
      colors: {
        'text-primary-light': '#000000',
        'text-primary-dark': '#ffffff',
        'brand-primary': 'var(--color-primary)',
        'brand-primary-hover': 'var(--color-primary-hover)',
        'brand-secondary': 'var(--color-secondary)',
        'brand-secondary-hover': 'var(--color-secondary-hover)',
        'brand-accent': 'var(--color-accent)',
        'brand-text': 'var(--color-text)',
        'brand-bg-secondary': 'var(--color-bg-secondary)',
        'brand-success': 'var(--color-success)',
        'brand-error': 'var(--color-error)',
        'brand-warning': 'var(--color-warning)',
        'orange-primary': 'var(--color-primary)',
        success: 'var(--color-success)',
      },
      borderColor: {
        'brand-primary': 'var(--color-primary)',
        'brand-secondary': 'var(--color-secondary)',
        'brand-accent': 'var(--color-accent)',
      },
      fontFamily: {
        lexend: 'var(--font-main, "Lexend Deca"), sans-serif',
        orbitron: 'var(--font-headings, "Orbitron"), sans-serif',
        main: 'var(--font-main, "Lexend Deca"), sans-serif',
        headings: 'var(--font-headings, "Orbitron"), sans-serif',
      },
    },
  },
  plugins: [],
};
